export const ADD_ITEM = 'ADD_ITEM'
export const UPDATE_ITEM = 'UPDATE_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const SET_ITEMS = 'SET_ITEMS'
export const SET_SLIDER_ITEMS = 'SET_SLIDER_ITEMS'
export const SET_TOKEN = 'SET_TOKEN'
